<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>a9e057c0-8f59-471c-841d-e7b816932153</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add "" to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
